/*---------------------------------------------------------------------+\
|																		|
|				Copyright 1986 .. 1996 Grizzly Software					|
|					a division of Bear Consulting Group					|
|						  All Rights Reserved							|
|																		|
|	This software-file/document, in whole or in part, including			|
|	the structures and the procedures described herein, may not			|
|	be provided or otherwise made available without prior written		|
|	authorization.  In case of authorized or unauthorized				|
|	publication or duplication, copyright is claimed.					|
|																		|
\+---------------------------------------------------------------------*/
/*---------------------------------------------------------------------+\
|
|	remtempl.cpp  --  brief description of what template.cpp is for
|
|	Purpose:
|	Author and Date:	J.Griswold			13-Jan-1996
|
| optional topics (delete if not used)
|	Usage:
|	Restrictions/Warnings:
|	Algorithms/Formats:
|	References:
|	Notes:
|
\+---------------------------------------------------------------------*/
/*---------------------------------------------------------------------+\
|
|	Revision History:
|
	13-Jan-1996			J.Griswold
		Initial Revision
|
\+---------------------------------------------------------------------*/
/*---------------------------------------------------------------------+\
|																		|
|	Include Files														|
|																		|
\+---------------------------------------------------------------------*/
#include "xpview.h"
#include "zcatitem.h"
/*---------------------------------------------------------------------+\
|																		|
|	Local defines / constants											|
|																		|
\+---------------------------------------------------------------------*/
/*---------------------------------------------------------------------+\
|																		|
|	Local Type Definitions												|
|																		|
\+---------------------------------------------------------------------*/
/*---------------------------------------------------------------------+\
|																		|
|	Private Global Variables											|
|																		|
\+---------------------------------------------------------------------*/
/*---------------------------------------------------------------------+\
|																		|
|	Public Global Variables												|
|																		|
\+---------------------------------------------------------------------*/
/*---------------------------------------------------------------------+\
|																		|
|	External Variables													|
|																		|
\+---------------------------------------------------------------------*/
/*=====================================================================+\
||																		|
||	 Code																|
||																		|
\+=====================================================================*/
//template class XPScrollViewt<PEGASUS_ViewBase>;
template class ZArray<ZCatalogItemPtr>;
template class ZArray<ZCatItemID>;
/*---------------------------------------------------------------------+\

 *  NAME:	someFunction - brief statement

 *  DESCRIPTION:

 *  AUTHOR: J.Griswold			DATE:	dd-mmm-1995

\+---------------------------------------------------------------------*/

