//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by RMND.RC
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_REMINDTYPE                  129
#define IDD_WINDOWBAR                   130
#define IDS_FONTSLABEL                  150
#define IDS_FONTSMESSAGE                151
#define IDC_EDIT1                       1002
#define ID_VIEW_PENDING                 32771
#define ID_VIEW_WEEKLY                  32772
#define ID_VIEW_MONTHLY                 32773
#define ID_VIEW_YEARLY                  32774
#define ID_VIEW_CALENDAR                32775
#define ID_NAVIGATE_NEXT                32776
#define ID_NAVIGATE_PREVIOUS            32777

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        131
#define _APS_NEXT_COMMAND_VALUE         32778
#define _APS_NEXT_CONTROL_VALUE         1003
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
